// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSFCJob;
import mingh.research.model.GSFCJobDataOnDemand;
import mingh.research.model.GSFCJobIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSFCJobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSFCJobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSFCJobIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSFCJobIntegrationTest: @Transactional;
    
    @Autowired
    GSFCJobDataOnDemand GSFCJobIntegrationTest.dod;
    
    @Test
    public void GSFCJobIntegrationTest.testCountGSFCJobs() {
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", dod.getRandomGSFCJob());
        long count = GSFCJob.countGSFCJobs();
        Assert.assertTrue("Counter for 'GSFCJob' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSFCJobIntegrationTest.testFindGSFCJob() {
        GSFCJob obj = dod.getRandomGSFCJob();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to provide an identifier", id);
        obj = GSFCJob.findGSFCJob(id);
        Assert.assertNotNull("Find method for 'GSFCJob' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSFCJob' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSFCJobIntegrationTest.testFindAllGSFCJobs() {
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", dod.getRandomGSFCJob());
        long count = GSFCJob.countGSFCJobs();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSFCJob', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSFCJob> result = GSFCJob.findAllGSFCJobs();
        Assert.assertNotNull("Find all method for 'GSFCJob' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSFCJob' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSFCJobIntegrationTest.testFindGSFCJobEntries() {
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", dod.getRandomGSFCJob());
        long count = GSFCJob.countGSFCJobs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSFCJob> result = GSFCJob.findGSFCJobEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSFCJob' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSFCJob' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSFCJobIntegrationTest.testFlush() {
        GSFCJob obj = dod.getRandomGSFCJob();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to provide an identifier", id);
        obj = GSFCJob.findGSFCJob(id);
        Assert.assertNotNull("Find method for 'GSFCJob' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSFCJob(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSFCJob' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSFCJobIntegrationTest.testMergeUpdate() {
        GSFCJob obj = dod.getRandomGSFCJob();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to provide an identifier", id);
        obj = GSFCJob.findGSFCJob(id);
        boolean modified =  dod.modifyGSFCJob(obj);
        Integer currentVersion = obj.getVersion();
        GSFCJob merged = (GSFCJob)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSFCJob' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSFCJobIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", dod.getRandomGSFCJob());
        GSFCJob obj = dod.getNewTransientGSFCJob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSFCJob' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSFCJob' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSFCJobIntegrationTest.testRemove() {
        GSFCJob obj = dod.getRandomGSFCJob();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSFCJob' failed to provide an identifier", id);
        obj = GSFCJob.findGSFCJob(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSFCJob' with identifier '" + id + "'", GSFCJob.findGSFCJob(id));
    }
    
}
