// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mingh.research.model.GSNCJobDataOnDemand;
import mingh.research.model.GSNCOptimizationProcess;
import mingh.research.model.GSNCOptimizationProcessDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GSNCOptimizationProcessDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GSNCOptimizationProcessDataOnDemand: @Component;
    
    private Random GSNCOptimizationProcessDataOnDemand.rnd = new SecureRandom();
    
    private List<GSNCOptimizationProcess> GSNCOptimizationProcessDataOnDemand.data;
    
    @Autowired
    GSNCJobDataOnDemand GSNCOptimizationProcessDataOnDemand.gSNCJobDataOnDemand;
    
    public GSNCOptimizationProcess GSNCOptimizationProcessDataOnDemand.getNewTransientGSNCOptimizationProcess(int index) {
        GSNCOptimizationProcess obj = new GSNCOptimizationProcess();
        setAlphaHOMOs(obj, index);
        setAlphaLUMOs(obj, index);
        setBetaHOMOs(obj, index);
        setBetaLUMOs(obj, index);
        setDetailedForces(obj, index);
        setEnergies(obj, index);
        setForces(obj, index);
        setGeometries(obj, index);
        setUniqueName(obj, index);
        return obj;
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setAlphaHOMOs(GSNCOptimizationProcess obj, int index) {
        String alphaHOMOs = "alphaHOMOs_" + index;
        if (alphaHOMOs.length() > 10000) {
            alphaHOMOs = alphaHOMOs.substring(0, 10000);
        }
        obj.setAlphaHOMOs(alphaHOMOs);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setAlphaLUMOs(GSNCOptimizationProcess obj, int index) {
        String alphaLUMOs = "alphaLUMOs_" + index;
        if (alphaLUMOs.length() > 10000) {
            alphaLUMOs = alphaLUMOs.substring(0, 10000);
        }
        obj.setAlphaLUMOs(alphaLUMOs);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setBetaHOMOs(GSNCOptimizationProcess obj, int index) {
        String betaHOMOs = "betaHOMOs_" + index;
        if (betaHOMOs.length() > 10000) {
            betaHOMOs = betaHOMOs.substring(0, 10000);
        }
        obj.setBetaHOMOs(betaHOMOs);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setBetaLUMOs(GSNCOptimizationProcess obj, int index) {
        String betaLUMOs = "betaLUMOs_" + index;
        if (betaLUMOs.length() > 10000) {
            betaLUMOs = betaLUMOs.substring(0, 10000);
        }
        obj.setBetaLUMOs(betaLUMOs);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setDetailedForces(GSNCOptimizationProcess obj, int index) {
        byte[] detailedForces = String.valueOf(index).getBytes();
        obj.setDetailedForces(detailedForces);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setEnergies(GSNCOptimizationProcess obj, int index) {
        String energies = "energies_" + index;
        if (energies.length() > 10000) {
            energies = energies.substring(0, 10000);
        }
        obj.setEnergies(energies);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setForces(GSNCOptimizationProcess obj, int index) {
        String forces = "forces_" + index;
        if (forces.length() > 10000) {
            forces = forces.substring(0, 10000);
        }
        obj.setForces(forces);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setGeometries(GSNCOptimizationProcess obj, int index) {
        byte[] geometries = String.valueOf(index).getBytes();
        obj.setGeometries(geometries);
    }
    
    public void GSNCOptimizationProcessDataOnDemand.setUniqueName(GSNCOptimizationProcess obj, int index) {
        String uniqueName = "uniqueName_" + index;
        if (uniqueName.length() > 100) {
            uniqueName = uniqueName.substring(0, 100);
        }
        obj.setUniqueName(uniqueName);
    }
    
    public GSNCOptimizationProcess GSNCOptimizationProcessDataOnDemand.getSpecificGSNCOptimizationProcess(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GSNCOptimizationProcess obj = data.get(index);
        Long id = obj.getId();
        return GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
    }
    
    public GSNCOptimizationProcess GSNCOptimizationProcessDataOnDemand.getRandomGSNCOptimizationProcess() {
        init();
        GSNCOptimizationProcess obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
    }
    
    public boolean GSNCOptimizationProcessDataOnDemand.modifyGSNCOptimizationProcess(GSNCOptimizationProcess obj) {
        return false;
    }
    
    public void GSNCOptimizationProcessDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = GSNCOptimizationProcess.findGSNCOptimizationProcessEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GSNCOptimizationProcess' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GSNCOptimizationProcess>();
        for (int i = 0; i < 10; i++) {
            GSNCOptimizationProcess obj = getNewTransientGSNCOptimizationProcess(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
