// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSNCJobIRProperty;
import mingh.research.model.GSNCJobIRPropertyDataOnDemand;
import mingh.research.model.GSNCJobIRPropertyIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSNCJobIRPropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSNCJobIRPropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSNCJobIRPropertyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSNCJobIRPropertyIntegrationTest: @Transactional;
    
    @Autowired
    GSNCJobIRPropertyDataOnDemand GSNCJobIRPropertyIntegrationTest.dod;
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testCountGSNCJobIRPropertys() {
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", dod.getRandomGSNCJobIRProperty());
        long count = GSNCJobIRProperty.countGSNCJobIRPropertys();
        Assert.assertTrue("Counter for 'GSNCJobIRProperty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testFindGSNCJobIRProperty() {
        GSNCJobIRProperty obj = dod.getRandomGSNCJobIRProperty();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to provide an identifier", id);
        obj = GSNCJobIRProperty.findGSNCJobIRProperty(id);
        Assert.assertNotNull("Find method for 'GSNCJobIRProperty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSNCJobIRProperty' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testFindAllGSNCJobIRPropertys() {
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", dod.getRandomGSNCJobIRProperty());
        long count = GSNCJobIRProperty.countGSNCJobIRPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSNCJobIRProperty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSNCJobIRProperty> result = GSNCJobIRProperty.findAllGSNCJobIRPropertys();
        Assert.assertNotNull("Find all method for 'GSNCJobIRProperty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSNCJobIRProperty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testFindGSNCJobIRPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", dod.getRandomGSNCJobIRProperty());
        long count = GSNCJobIRProperty.countGSNCJobIRPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSNCJobIRProperty> result = GSNCJobIRProperty.findGSNCJobIRPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSNCJobIRProperty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSNCJobIRProperty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testFlush() {
        GSNCJobIRProperty obj = dod.getRandomGSNCJobIRProperty();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to provide an identifier", id);
        obj = GSNCJobIRProperty.findGSNCJobIRProperty(id);
        Assert.assertNotNull("Find method for 'GSNCJobIRProperty' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSNCJobIRProperty(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSNCJobIRProperty' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testMergeUpdate() {
        GSNCJobIRProperty obj = dod.getRandomGSNCJobIRProperty();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to provide an identifier", id);
        obj = GSNCJobIRProperty.findGSNCJobIRProperty(id);
        boolean modified =  dod.modifyGSNCJobIRProperty(obj);
        Integer currentVersion = obj.getVersion();
        GSNCJobIRProperty merged = (GSNCJobIRProperty)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSNCJobIRProperty' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", dod.getRandomGSNCJobIRProperty());
        GSNCJobIRProperty obj = dod.getNewTransientGSNCJobIRProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSNCJobIRProperty' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSNCJobIRProperty' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSNCJobIRPropertyIntegrationTest.testRemove() {
        GSNCJobIRProperty obj = dod.getRandomGSNCJobIRProperty();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobIRProperty' failed to provide an identifier", id);
        obj = GSNCJobIRProperty.findGSNCJobIRProperty(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSNCJobIRProperty' with identifier '" + id + "'", GSNCJobIRProperty.findGSNCJobIRProperty(id));
    }
    
}
