// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSNCOptimizationProcess;
import mingh.research.model.GSNCOptimizationProcessDataOnDemand;
import mingh.research.model.GSNCOptimizationProcessIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSNCOptimizationProcessIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSNCOptimizationProcessIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSNCOptimizationProcessIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSNCOptimizationProcessIntegrationTest: @Transactional;
    
    @Autowired
    GSNCOptimizationProcessDataOnDemand GSNCOptimizationProcessIntegrationTest.dod;
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testCountGSNCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", dod.getRandomGSNCOptimizationProcess());
        long count = GSNCOptimizationProcess.countGSNCOptimizationProcesses();
        Assert.assertTrue("Counter for 'GSNCOptimizationProcess' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testFindGSNCOptimizationProcess() {
        GSNCOptimizationProcess obj = dod.getRandomGSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to provide an identifier", id);
        obj = GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'GSNCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSNCOptimizationProcess' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testFindAllGSNCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", dod.getRandomGSNCOptimizationProcess());
        long count = GSNCOptimizationProcess.countGSNCOptimizationProcesses();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSNCOptimizationProcess', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSNCOptimizationProcess> result = GSNCOptimizationProcess.findAllGSNCOptimizationProcesses();
        Assert.assertNotNull("Find all method for 'GSNCOptimizationProcess' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSNCOptimizationProcess' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testFindGSNCOptimizationProcessEntries() {
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", dod.getRandomGSNCOptimizationProcess());
        long count = GSNCOptimizationProcess.countGSNCOptimizationProcesses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSNCOptimizationProcess> result = GSNCOptimizationProcess.findGSNCOptimizationProcessEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSNCOptimizationProcess' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSNCOptimizationProcess' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testFlush() {
        GSNCOptimizationProcess obj = dod.getRandomGSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to provide an identifier", id);
        obj = GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'GSNCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSNCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSNCOptimizationProcess' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testMergeUpdate() {
        GSNCOptimizationProcess obj = dod.getRandomGSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to provide an identifier", id);
        obj = GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
        boolean modified =  dod.modifyGSNCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        GSNCOptimizationProcess merged = (GSNCOptimizationProcess)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSNCOptimizationProcess' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", dod.getRandomGSNCOptimizationProcess());
        GSNCOptimizationProcess obj = dod.getNewTransientGSNCOptimizationProcess(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSNCOptimizationProcess' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSNCOptimizationProcess' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSNCOptimizationProcessIntegrationTest.testRemove() {
        GSNCOptimizationProcess obj = dod.getRandomGSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCOptimizationProcess' failed to provide an identifier", id);
        obj = GSNCOptimizationProcess.findGSNCOptimizationProcess(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSNCOptimizationProcess' with identifier '" + id + "'", GSNCOptimizationProcess.findGSNCOptimizationProcess(id));
    }
    
}
