// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSNCJobStep;
import mingh.research.model.GSNCJobStepDataOnDemand;
import mingh.research.model.GSNCJobStepIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSNCJobStepIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSNCJobStepIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSNCJobStepIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSNCJobStepIntegrationTest: @Transactional;
    
    @Autowired
    GSNCJobStepDataOnDemand GSNCJobStepIntegrationTest.dod;
    
    @Test
    public void GSNCJobStepIntegrationTest.testCountGSNCJobSteps() {
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", dod.getRandomGSNCJobStep());
        long count = GSNCJobStep.countGSNCJobSteps();
        Assert.assertTrue("Counter for 'GSNCJobStep' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testFindGSNCJobStep() {
        GSNCJobStep obj = dod.getRandomGSNCJobStep();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to provide an identifier", id);
        obj = GSNCJobStep.findGSNCJobStep(id);
        Assert.assertNotNull("Find method for 'GSNCJobStep' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSNCJobStep' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testFindAllGSNCJobSteps() {
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", dod.getRandomGSNCJobStep());
        long count = GSNCJobStep.countGSNCJobSteps();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSNCJobStep', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSNCJobStep> result = GSNCJobStep.findAllGSNCJobSteps();
        Assert.assertNotNull("Find all method for 'GSNCJobStep' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSNCJobStep' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testFindGSNCJobStepEntries() {
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", dod.getRandomGSNCJobStep());
        long count = GSNCJobStep.countGSNCJobSteps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSNCJobStep> result = GSNCJobStep.findGSNCJobStepEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSNCJobStep' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSNCJobStep' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testFlush() {
        GSNCJobStep obj = dod.getRandomGSNCJobStep();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to provide an identifier", id);
        obj = GSNCJobStep.findGSNCJobStep(id);
        Assert.assertNotNull("Find method for 'GSNCJobStep' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSNCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSNCJobStep' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testMergeUpdate() {
        GSNCJobStep obj = dod.getRandomGSNCJobStep();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to provide an identifier", id);
        obj = GSNCJobStep.findGSNCJobStep(id);
        boolean modified =  dod.modifyGSNCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        GSNCJobStep merged = (GSNCJobStep)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSNCJobStep' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", dod.getRandomGSNCJobStep());
        GSNCJobStep obj = dod.getNewTransientGSNCJobStep(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSNCJobStep' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSNCJobStep' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSNCJobStepIntegrationTest.testRemove() {
        GSNCJobStep obj = dod.getRandomGSNCJobStep();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJobStep' failed to provide an identifier", id);
        obj = GSNCJobStep.findGSNCJobStep(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSNCJobStep' with identifier '" + id + "'", GSNCJobStep.findGSNCJobStep(id));
    }
    
}
