// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSNCStoredFiles;
import mingh.research.model.GSNCStoredFilesDataOnDemand;
import mingh.research.model.GSNCStoredFilesIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSNCStoredFilesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSNCStoredFilesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSNCStoredFilesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSNCStoredFilesIntegrationTest: @Transactional;
    
    @Autowired
    GSNCStoredFilesDataOnDemand GSNCStoredFilesIntegrationTest.dod;
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testCountGSNCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", dod.getRandomGSNCStoredFiles());
        long count = GSNCStoredFiles.countGSNCStoredFileses();
        Assert.assertTrue("Counter for 'GSNCStoredFiles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testFindGSNCStoredFiles() {
        GSNCStoredFiles obj = dod.getRandomGSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to provide an identifier", id);
        obj = GSNCStoredFiles.findGSNCStoredFiles(id);
        Assert.assertNotNull("Find method for 'GSNCStoredFiles' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSNCStoredFiles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testFindAllGSNCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", dod.getRandomGSNCStoredFiles());
        long count = GSNCStoredFiles.countGSNCStoredFileses();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSNCStoredFiles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSNCStoredFiles> result = GSNCStoredFiles.findAllGSNCStoredFileses();
        Assert.assertNotNull("Find all method for 'GSNCStoredFiles' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSNCStoredFiles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testFindGSNCStoredFilesEntries() {
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", dod.getRandomGSNCStoredFiles());
        long count = GSNCStoredFiles.countGSNCStoredFileses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSNCStoredFiles> result = GSNCStoredFiles.findGSNCStoredFilesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSNCStoredFiles' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSNCStoredFiles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testFlush() {
        GSNCStoredFiles obj = dod.getRandomGSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to provide an identifier", id);
        obj = GSNCStoredFiles.findGSNCStoredFiles(id);
        Assert.assertNotNull("Find method for 'GSNCStoredFiles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSNCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSNCStoredFiles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testMergeUpdate() {
        GSNCStoredFiles obj = dod.getRandomGSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to provide an identifier", id);
        obj = GSNCStoredFiles.findGSNCStoredFiles(id);
        boolean modified =  dod.modifyGSNCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        GSNCStoredFiles merged = (GSNCStoredFiles)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSNCStoredFiles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", dod.getRandomGSNCStoredFiles());
        GSNCStoredFiles obj = dod.getNewTransientGSNCStoredFiles(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSNCStoredFiles' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSNCStoredFiles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSNCStoredFilesIntegrationTest.testRemove() {
        GSNCStoredFiles obj = dod.getRandomGSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCStoredFiles' failed to provide an identifier", id);
        obj = GSNCStoredFiles.findGSNCStoredFiles(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSNCStoredFiles' with identifier '" + id + "'", GSNCStoredFiles.findGSNCStoredFiles(id));
    }
    
}
