// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.GSNCJob;
import mingh.research.model.GSNCJobDataOnDemand;
import mingh.research.model.GSNCJobIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GSNCJobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GSNCJobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GSNCJobIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GSNCJobIntegrationTest: @Transactional;
    
    @Autowired
    GSNCJobDataOnDemand GSNCJobIntegrationTest.dod;
    
    @Test
    public void GSNCJobIntegrationTest.testCountGSNCJobs() {
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", dod.getRandomGSNCJob());
        long count = GSNCJob.countGSNCJobs();
        Assert.assertTrue("Counter for 'GSNCJob' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GSNCJobIntegrationTest.testFindGSNCJob() {
        GSNCJob obj = dod.getRandomGSNCJob();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to provide an identifier", id);
        obj = GSNCJob.findGSNCJob(id);
        Assert.assertNotNull("Find method for 'GSNCJob' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GSNCJob' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GSNCJobIntegrationTest.testFindAllGSNCJobs() {
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", dod.getRandomGSNCJob());
        long count = GSNCJob.countGSNCJobs();
        Assert.assertTrue("Too expensive to perform a find all test for 'GSNCJob', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GSNCJob> result = GSNCJob.findAllGSNCJobs();
        Assert.assertNotNull("Find all method for 'GSNCJob' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GSNCJob' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GSNCJobIntegrationTest.testFindGSNCJobEntries() {
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", dod.getRandomGSNCJob());
        long count = GSNCJob.countGSNCJobs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GSNCJob> result = GSNCJob.findGSNCJobEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GSNCJob' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GSNCJob' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GSNCJobIntegrationTest.testFlush() {
        GSNCJob obj = dod.getRandomGSNCJob();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to provide an identifier", id);
        obj = GSNCJob.findGSNCJob(id);
        Assert.assertNotNull("Find method for 'GSNCJob' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGSNCJob(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GSNCJob' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobIntegrationTest.testMergeUpdate() {
        GSNCJob obj = dod.getRandomGSNCJob();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to provide an identifier", id);
        obj = GSNCJob.findGSNCJob(id);
        boolean modified =  dod.modifyGSNCJob(obj);
        Integer currentVersion = obj.getVersion();
        GSNCJob merged = (GSNCJob)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GSNCJob' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GSNCJobIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", dod.getRandomGSNCJob());
        GSNCJob obj = dod.getNewTransientGSNCJob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GSNCJob' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GSNCJob' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GSNCJobIntegrationTest.testRemove() {
        GSNCJob obj = dod.getRandomGSNCJob();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GSNCJob' failed to provide an identifier", id);
        obj = GSNCJob.findGSNCJob(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GSNCJob' with identifier '" + id + "'", GSNCJob.findGSNCJob(id));
    }
    
}
