// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.JobResource;
import mingh.research.model.JobResourceDataOnDemand;
import mingh.research.model.JobResourceIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobResourceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobResourceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobResourceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobResourceIntegrationTest: @Transactional;
    
    @Autowired
    JobResourceDataOnDemand JobResourceIntegrationTest.dod;
    
    @Test
    public void JobResourceIntegrationTest.testCountJobResources() {
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", dod.getRandomJobResource());
        long count = JobResource.countJobResources();
        Assert.assertTrue("Counter for 'JobResource' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobResourceIntegrationTest.testFindJobResource() {
        JobResource obj = dod.getRandomJobResource();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to provide an identifier", id);
        obj = JobResource.findJobResource(id);
        Assert.assertNotNull("Find method for 'JobResource' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JobResource' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobResourceIntegrationTest.testFindAllJobResources() {
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", dod.getRandomJobResource());
        long count = JobResource.countJobResources();
        Assert.assertTrue("Too expensive to perform a find all test for 'JobResource', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JobResource> result = JobResource.findAllJobResources();
        Assert.assertNotNull("Find all method for 'JobResource' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JobResource' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobResourceIntegrationTest.testFindJobResourceEntries() {
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", dod.getRandomJobResource());
        long count = JobResource.countJobResources();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JobResource> result = JobResource.findJobResourceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JobResource' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JobResource' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobResourceIntegrationTest.testFlush() {
        JobResource obj = dod.getRandomJobResource();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to provide an identifier", id);
        obj = JobResource.findJobResource(id);
        Assert.assertNotNull("Find method for 'JobResource' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJobResource(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JobResource' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobResourceIntegrationTest.testMergeUpdate() {
        JobResource obj = dod.getRandomJobResource();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to provide an identifier", id);
        obj = JobResource.findJobResource(id);
        boolean modified =  dod.modifyJobResource(obj);
        Integer currentVersion = obj.getVersion();
        JobResource merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JobResource' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobResourceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", dod.getRandomJobResource());
        JobResource obj = dod.getNewTransientJobResource(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JobResource' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JobResource' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JobResource' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobResourceIntegrationTest.testRemove() {
        JobResource obj = dod.getRandomJobResource();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobResource' failed to provide an identifier", id);
        obj = JobResource.findJobResource(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JobResource' with identifier '" + id + "'", JobResource.findJobResource(id));
    }
    
}
