// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSFCOptimizationProcess;
import mingh.research.model.TSFCOptimizationProcessDataOnDemand;
import mingh.research.model.TSFCOptimizationProcessIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSFCOptimizationProcessIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSFCOptimizationProcessIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSFCOptimizationProcessIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSFCOptimizationProcessIntegrationTest: @Transactional;
    
    @Autowired
    TSFCOptimizationProcessDataOnDemand TSFCOptimizationProcessIntegrationTest.dod;
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testCountTSFCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", dod.getRandomTSFCOptimizationProcess());
        long count = TSFCOptimizationProcess.countTSFCOptimizationProcesses();
        Assert.assertTrue("Counter for 'TSFCOptimizationProcess' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testFindTSFCOptimizationProcess() {
        TSFCOptimizationProcess obj = dod.getRandomTSFCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to provide an identifier", id);
        obj = TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'TSFCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSFCOptimizationProcess' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testFindAllTSFCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", dod.getRandomTSFCOptimizationProcess());
        long count = TSFCOptimizationProcess.countTSFCOptimizationProcesses();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSFCOptimizationProcess', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSFCOptimizationProcess> result = TSFCOptimizationProcess.findAllTSFCOptimizationProcesses();
        Assert.assertNotNull("Find all method for 'TSFCOptimizationProcess' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSFCOptimizationProcess' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testFindTSFCOptimizationProcessEntries() {
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", dod.getRandomTSFCOptimizationProcess());
        long count = TSFCOptimizationProcess.countTSFCOptimizationProcesses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSFCOptimizationProcess> result = TSFCOptimizationProcess.findTSFCOptimizationProcessEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSFCOptimizationProcess' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSFCOptimizationProcess' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testFlush() {
        TSFCOptimizationProcess obj = dod.getRandomTSFCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to provide an identifier", id);
        obj = TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'TSFCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSFCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSFCOptimizationProcess' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testMergeUpdate() {
        TSFCOptimizationProcess obj = dod.getRandomTSFCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to provide an identifier", id);
        obj = TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
        boolean modified =  dod.modifyTSFCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        TSFCOptimizationProcess merged = (TSFCOptimizationProcess)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSFCOptimizationProcess' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", dod.getRandomTSFCOptimizationProcess());
        TSFCOptimizationProcess obj = dod.getNewTransientTSFCOptimizationProcess(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSFCOptimizationProcess' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSFCOptimizationProcess' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSFCOptimizationProcessIntegrationTest.testRemove() {
        TSFCOptimizationProcess obj = dod.getRandomTSFCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCOptimizationProcess' failed to provide an identifier", id);
        obj = TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSFCOptimizationProcess' with identifier '" + id + "'", TSFCOptimizationProcess.findTSFCOptimizationProcess(id));
    }
    
}
