// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import mingh.research.model.TSFCJobIRPropertyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TSFCJobIRPropertyDataOnDemand_Roo_Configurable {
    
    declare @type: TSFCJobIRPropertyDataOnDemand: @Configurable;
    
}
