// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSFCJob;
import mingh.research.model.TSFCJobDataOnDemand;
import mingh.research.model.TSFCJobIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSFCJobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSFCJobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSFCJobIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSFCJobIntegrationTest: @Transactional;
    
    @Autowired
    TSFCJobDataOnDemand TSFCJobIntegrationTest.dod;
    
    @Test
    public void TSFCJobIntegrationTest.testCountTSFCJobs() {
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", dod.getRandomTSFCJob());
        long count = TSFCJob.countTSFCJobs();
        Assert.assertTrue("Counter for 'TSFCJob' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSFCJobIntegrationTest.testFindTSFCJob() {
        TSFCJob obj = dod.getRandomTSFCJob();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to provide an identifier", id);
        obj = TSFCJob.findTSFCJob(id);
        Assert.assertNotNull("Find method for 'TSFCJob' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSFCJob' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSFCJobIntegrationTest.testFindAllTSFCJobs() {
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", dod.getRandomTSFCJob());
        long count = TSFCJob.countTSFCJobs();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSFCJob', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSFCJob> result = TSFCJob.findAllTSFCJobs();
        Assert.assertNotNull("Find all method for 'TSFCJob' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSFCJob' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSFCJobIntegrationTest.testFindTSFCJobEntries() {
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", dod.getRandomTSFCJob());
        long count = TSFCJob.countTSFCJobs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSFCJob> result = TSFCJob.findTSFCJobEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSFCJob' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSFCJob' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSFCJobIntegrationTest.testFlush() {
        TSFCJob obj = dod.getRandomTSFCJob();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to provide an identifier", id);
        obj = TSFCJob.findTSFCJob(id);
        Assert.assertNotNull("Find method for 'TSFCJob' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSFCJob(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSFCJob' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCJobIntegrationTest.testMergeUpdate() {
        TSFCJob obj = dod.getRandomTSFCJob();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to provide an identifier", id);
        obj = TSFCJob.findTSFCJob(id);
        boolean modified =  dod.modifyTSFCJob(obj);
        Integer currentVersion = obj.getVersion();
        TSFCJob merged = (TSFCJob)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSFCJob' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCJobIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", dod.getRandomTSFCJob());
        TSFCJob obj = dod.getNewTransientTSFCJob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSFCJob' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSFCJob' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSFCJobIntegrationTest.testRemove() {
        TSFCJob obj = dod.getRandomTSFCJob();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJob' failed to provide an identifier", id);
        obj = TSFCJob.findTSFCJob(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSFCJob' with identifier '" + id + "'", TSFCJob.findTSFCJob(id));
    }
    
}
