// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSFCStoredFiles;
import mingh.research.model.TSFCStoredFilesDataOnDemand;
import mingh.research.model.TSFCStoredFilesIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSFCStoredFilesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSFCStoredFilesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSFCStoredFilesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSFCStoredFilesIntegrationTest: @Transactional;
    
    @Autowired
    TSFCStoredFilesDataOnDemand TSFCStoredFilesIntegrationTest.dod;
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testCountTSFCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", dod.getRandomTSFCStoredFiles());
        long count = TSFCStoredFiles.countTSFCStoredFileses();
        Assert.assertTrue("Counter for 'TSFCStoredFiles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testFindTSFCStoredFiles() {
        TSFCStoredFiles obj = dod.getRandomTSFCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to provide an identifier", id);
        obj = TSFCStoredFiles.findTSFCStoredFiles(id);
        Assert.assertNotNull("Find method for 'TSFCStoredFiles' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSFCStoredFiles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testFindAllTSFCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", dod.getRandomTSFCStoredFiles());
        long count = TSFCStoredFiles.countTSFCStoredFileses();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSFCStoredFiles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSFCStoredFiles> result = TSFCStoredFiles.findAllTSFCStoredFileses();
        Assert.assertNotNull("Find all method for 'TSFCStoredFiles' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSFCStoredFiles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testFindTSFCStoredFilesEntries() {
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", dod.getRandomTSFCStoredFiles());
        long count = TSFCStoredFiles.countTSFCStoredFileses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSFCStoredFiles> result = TSFCStoredFiles.findTSFCStoredFilesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSFCStoredFiles' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSFCStoredFiles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testFlush() {
        TSFCStoredFiles obj = dod.getRandomTSFCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to provide an identifier", id);
        obj = TSFCStoredFiles.findTSFCStoredFiles(id);
        Assert.assertNotNull("Find method for 'TSFCStoredFiles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSFCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSFCStoredFiles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testMergeUpdate() {
        TSFCStoredFiles obj = dod.getRandomTSFCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to provide an identifier", id);
        obj = TSFCStoredFiles.findTSFCStoredFiles(id);
        boolean modified =  dod.modifyTSFCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        TSFCStoredFiles merged = (TSFCStoredFiles)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSFCStoredFiles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", dod.getRandomTSFCStoredFiles());
        TSFCStoredFiles obj = dod.getNewTransientTSFCStoredFiles(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSFCStoredFiles' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSFCStoredFiles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSFCStoredFilesIntegrationTest.testRemove() {
        TSFCStoredFiles obj = dod.getRandomTSFCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCStoredFiles' failed to provide an identifier", id);
        obj = TSFCStoredFiles.findTSFCStoredFiles(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSFCStoredFiles' with identifier '" + id + "'", TSFCStoredFiles.findTSFCStoredFiles(id));
    }
    
}
