// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mingh.research.model.TSFCJobDataOnDemand;
import mingh.research.model.TSFCOptimizationProcess;
import mingh.research.model.TSFCOptimizationProcessDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TSFCOptimizationProcessDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TSFCOptimizationProcessDataOnDemand: @Component;
    
    private Random TSFCOptimizationProcessDataOnDemand.rnd = new SecureRandom();
    
    private List<TSFCOptimizationProcess> TSFCOptimizationProcessDataOnDemand.data;
    
    @Autowired
    TSFCJobDataOnDemand TSFCOptimizationProcessDataOnDemand.tSFCJobDataOnDemand;
    
    public TSFCOptimizationProcess TSFCOptimizationProcessDataOnDemand.getNewTransientTSFCOptimizationProcess(int index) {
        TSFCOptimizationProcess obj = new TSFCOptimizationProcess();
        setAlphaHOMOs(obj, index);
        setAlphaLUMOs(obj, index);
        setBetaHOMOs(obj, index);
        setBetaLUMOs(obj, index);
        setDetailedForces(obj, index);
        setEnergies(obj, index);
        setForces(obj, index);
        setGeometries(obj, index);
        setUniqueName(obj, index);
        return obj;
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setAlphaHOMOs(TSFCOptimizationProcess obj, int index) {
        String alphaHOMOs = "alphaHOMOs_" + index;
        if (alphaHOMOs.length() > 10000) {
            alphaHOMOs = alphaHOMOs.substring(0, 10000);
        }
        obj.setAlphaHOMOs(alphaHOMOs);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setAlphaLUMOs(TSFCOptimizationProcess obj, int index) {
        String alphaLUMOs = "alphaLUMOs_" + index;
        if (alphaLUMOs.length() > 10000) {
            alphaLUMOs = alphaLUMOs.substring(0, 10000);
        }
        obj.setAlphaLUMOs(alphaLUMOs);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setBetaHOMOs(TSFCOptimizationProcess obj, int index) {
        String betaHOMOs = "betaHOMOs_" + index;
        if (betaHOMOs.length() > 10000) {
            betaHOMOs = betaHOMOs.substring(0, 10000);
        }
        obj.setBetaHOMOs(betaHOMOs);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setBetaLUMOs(TSFCOptimizationProcess obj, int index) {
        String betaLUMOs = "betaLUMOs_" + index;
        if (betaLUMOs.length() > 10000) {
            betaLUMOs = betaLUMOs.substring(0, 10000);
        }
        obj.setBetaLUMOs(betaLUMOs);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setDetailedForces(TSFCOptimizationProcess obj, int index) {
        byte[] detailedForces = String.valueOf(index).getBytes();
        obj.setDetailedForces(detailedForces);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setEnergies(TSFCOptimizationProcess obj, int index) {
        String energies = "energies_" + index;
        if (energies.length() > 10000) {
            energies = energies.substring(0, 10000);
        }
        obj.setEnergies(energies);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setForces(TSFCOptimizationProcess obj, int index) {
        String forces = "forces_" + index;
        if (forces.length() > 10000) {
            forces = forces.substring(0, 10000);
        }
        obj.setForces(forces);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setGeometries(TSFCOptimizationProcess obj, int index) {
        byte[] geometries = String.valueOf(index).getBytes();
        obj.setGeometries(geometries);
    }
    
    public void TSFCOptimizationProcessDataOnDemand.setUniqueName(TSFCOptimizationProcess obj, int index) {
        String uniqueName = "uniqueName_" + index;
        if (uniqueName.length() > 100) {
            uniqueName = uniqueName.substring(0, 100);
        }
        obj.setUniqueName(uniqueName);
    }
    
    public TSFCOptimizationProcess TSFCOptimizationProcessDataOnDemand.getSpecificTSFCOptimizationProcess(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TSFCOptimizationProcess obj = data.get(index);
        Long id = obj.getId();
        return TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
    }
    
    public TSFCOptimizationProcess TSFCOptimizationProcessDataOnDemand.getRandomTSFCOptimizationProcess() {
        init();
        TSFCOptimizationProcess obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TSFCOptimizationProcess.findTSFCOptimizationProcess(id);
    }
    
    public boolean TSFCOptimizationProcessDataOnDemand.modifyTSFCOptimizationProcess(TSFCOptimizationProcess obj) {
        return false;
    }
    
    public void TSFCOptimizationProcessDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TSFCOptimizationProcess.findTSFCOptimizationProcessEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TSFCOptimizationProcess' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TSFCOptimizationProcess>();
        for (int i = 0; i < 10; i++) {
            TSFCOptimizationProcess obj = getNewTransientTSFCOptimizationProcess(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
