// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSFCJobStep;
import mingh.research.model.TSFCJobStepDataOnDemand;
import mingh.research.model.TSFCJobStepIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSFCJobStepIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSFCJobStepIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSFCJobStepIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSFCJobStepIntegrationTest: @Transactional;
    
    @Autowired
    TSFCJobStepDataOnDemand TSFCJobStepIntegrationTest.dod;
    
    @Test
    public void TSFCJobStepIntegrationTest.testCountTSFCJobSteps() {
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", dod.getRandomTSFCJobStep());
        long count = TSFCJobStep.countTSFCJobSteps();
        Assert.assertTrue("Counter for 'TSFCJobStep' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testFindTSFCJobStep() {
        TSFCJobStep obj = dod.getRandomTSFCJobStep();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to provide an identifier", id);
        obj = TSFCJobStep.findTSFCJobStep(id);
        Assert.assertNotNull("Find method for 'TSFCJobStep' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSFCJobStep' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testFindAllTSFCJobSteps() {
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", dod.getRandomTSFCJobStep());
        long count = TSFCJobStep.countTSFCJobSteps();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSFCJobStep', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSFCJobStep> result = TSFCJobStep.findAllTSFCJobSteps();
        Assert.assertNotNull("Find all method for 'TSFCJobStep' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSFCJobStep' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testFindTSFCJobStepEntries() {
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", dod.getRandomTSFCJobStep());
        long count = TSFCJobStep.countTSFCJobSteps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSFCJobStep> result = TSFCJobStep.findTSFCJobStepEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSFCJobStep' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSFCJobStep' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testFlush() {
        TSFCJobStep obj = dod.getRandomTSFCJobStep();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to provide an identifier", id);
        obj = TSFCJobStep.findTSFCJobStep(id);
        Assert.assertNotNull("Find method for 'TSFCJobStep' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSFCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSFCJobStep' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testMergeUpdate() {
        TSFCJobStep obj = dod.getRandomTSFCJobStep();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to provide an identifier", id);
        obj = TSFCJobStep.findTSFCJobStep(id);
        boolean modified =  dod.modifyTSFCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        TSFCJobStep merged = (TSFCJobStep)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSFCJobStep' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", dod.getRandomTSFCJobStep());
        TSFCJobStep obj = dod.getNewTransientTSFCJobStep(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSFCJobStep' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSFCJobStep' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSFCJobStepIntegrationTest.testRemove() {
        TSFCJobStep obj = dod.getRandomTSFCJobStep();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSFCJobStep' failed to provide an identifier", id);
        obj = TSFCJobStep.findTSFCJobStep(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSFCJobStep' with identifier '" + id + "'", TSFCJobStep.findTSFCJobStep(id));
    }
    
}
