// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mingh.research.model.ReactionSiteTypeEnum;
import mingh.research.model.TSFCJob;
import mingh.research.model.TSFCJobDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect TSFCJobDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TSFCJobDataOnDemand: @Component;
    
    private Random TSFCJobDataOnDemand.rnd = new SecureRandom();
    
    private List<TSFCJob> TSFCJobDataOnDemand.data;
    
    public TSFCJob TSFCJobDataOnDemand.getNewTransientTSFCJob(int index) {
        TSFCJob obj = new TSFCJob();
        setAlphaHOMO(obj, index);
        setAlphaLUMO(obj, index);
        setAlphaOrbital(obj, index);
        setBetaHOMO(obj, index);
        setBetaLUMO(obj, index);
        setBetaOrbital(obj, index);
        setCluster(obj, index);
        setDetailedForce(obj, index);
        setEnergy(obj, index);
        setEnthalpy(obj, index);
        setForce(obj, index);
        setGeometry(obj, index);
        setGibbsEnergy(obj, index);
        setInputParams(obj, index);
        setInternalEnergy(obj, index);
        setMolecule(obj, index);
        setRelativePath(obj, index);
        setSiteType(obj, index);
        setSpin(obj, index);
        setStartGeometry(obj, index);
        setUniqueName(obj, index);
        setUnrestrictedSpinGuess(obj, index);
        setUnrestrictedSpinReal(obj, index);
        setZpe(obj, index);
        return obj;
    }
    
    public void TSFCJobDataOnDemand.setAlphaHOMO(TSFCJob obj, int index) {
        BigDecimal alphaHOMO = BigDecimal.valueOf(index);
        if (alphaHOMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            alphaHOMO = new BigDecimal("99999.99999");
        }
        obj.setAlphaHOMO(alphaHOMO);
    }
    
    public void TSFCJobDataOnDemand.setAlphaLUMO(TSFCJob obj, int index) {
        BigDecimal alphaLUMO = BigDecimal.valueOf(index);
        if (alphaLUMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            alphaLUMO = new BigDecimal("99999.99999");
        }
        obj.setAlphaLUMO(alphaLUMO);
    }
    
    public void TSFCJobDataOnDemand.setAlphaOrbital(TSFCJob obj, int index) {
        String alphaOrbital = "alphaOrbital_" + index;
        if (alphaOrbital.length() > 20000) {
            alphaOrbital = alphaOrbital.substring(0, 20000);
        }
        obj.setAlphaOrbital(alphaOrbital);
    }
    
    public void TSFCJobDataOnDemand.setBetaHOMO(TSFCJob obj, int index) {
        BigDecimal betaHOMO = BigDecimal.valueOf(index);
        if (betaHOMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            betaHOMO = new BigDecimal("99999.99999");
        }
        obj.setBetaHOMO(betaHOMO);
    }
    
    public void TSFCJobDataOnDemand.setBetaLUMO(TSFCJob obj, int index) {
        BigDecimal betaLUMO = BigDecimal.valueOf(index);
        if (betaLUMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            betaLUMO = new BigDecimal("99999.99999");
        }
        obj.setBetaLUMO(betaLUMO);
    }
    
    public void TSFCJobDataOnDemand.setBetaOrbital(TSFCJob obj, int index) {
        String betaOrbital = "betaOrbital_" + index;
        if (betaOrbital.length() > 20000) {
            betaOrbital = betaOrbital.substring(0, 20000);
        }
        obj.setBetaOrbital(betaOrbital);
    }
    
    public void TSFCJobDataOnDemand.setCluster(TSFCJob obj, int index) {
        String cluster = "cluster_" + index;
        if (cluster.length() > 10) {
            cluster = cluster.substring(0, 10);
        }
        obj.setCluster(cluster);
    }
    
    public void TSFCJobDataOnDemand.setDetailedForce(TSFCJob obj, int index) {
        String detailedForce = "detailedForce_" + index;
        if (detailedForce.length() > 5000) {
            detailedForce = detailedForce.substring(0, 5000);
        }
        obj.setDetailedForce(detailedForce);
    }
    
    public void TSFCJobDataOnDemand.setEnergy(TSFCJob obj, int index) {
        BigDecimal energy = BigDecimal.valueOf(index);
        if (energy.compareTo(new BigDecimal("99999.99999")) == 1) {
            energy = new BigDecimal("99999.99999");
        }
        obj.setEnergy(energy);
    }
    
    public void TSFCJobDataOnDemand.setEnthalpy(TSFCJob obj, int index) {
        BigDecimal enthalpy = BigDecimal.valueOf(index);
        if (enthalpy.compareTo(new BigDecimal("99999.99999")) == 1) {
            enthalpy = new BigDecimal("99999.99999");
        }
        obj.setEnthalpy(enthalpy);
    }
    
    public void TSFCJobDataOnDemand.setForce(TSFCJob obj, int index) {
        BigDecimal force = BigDecimal.valueOf(index);
        if (force.compareTo(new BigDecimal("99999.99999")) == 1) {
            force = new BigDecimal("99999.99999");
        }
        obj.setForce(force);
    }
    
    public void TSFCJobDataOnDemand.setGeometry(TSFCJob obj, int index) {
        String geometry = "geometry_" + index;
        if (geometry.length() > 5000) {
            geometry = geometry.substring(0, 5000);
        }
        obj.setGeometry(geometry);
    }
    
    public void TSFCJobDataOnDemand.setGibbsEnergy(TSFCJob obj, int index) {
        BigDecimal gibbsEnergy = BigDecimal.valueOf(index);
        if (gibbsEnergy.compareTo(new BigDecimal("99999.99999")) == 1) {
            gibbsEnergy = new BigDecimal("99999.99999");
        }
        obj.setGibbsEnergy(gibbsEnergy);
    }
    
    public void TSFCJobDataOnDemand.setInputParams(TSFCJob obj, int index) {
        String inputParams = "inputParams_" + index;
        if (inputParams.length() > 5000) {
            inputParams = inputParams.substring(0, 5000);
        }
        obj.setInputParams(inputParams);
    }
    
    public void TSFCJobDataOnDemand.setInternalEnergy(TSFCJob obj, int index) {
        BigDecimal internalEnergy = BigDecimal.valueOf(index);
        if (internalEnergy.compareTo(new BigDecimal("99999.99999")) == 1) {
            internalEnergy = new BigDecimal("99999.99999");
        }
        obj.setInternalEnergy(internalEnergy);
    }
    
    public void TSFCJobDataOnDemand.setMolecule(TSFCJob obj, int index) {
        String molecule = "molecule_" + index;
        if (molecule.length() > 50) {
            molecule = molecule.substring(0, 50);
        }
        obj.setMolecule(molecule);
    }
    
    public void TSFCJobDataOnDemand.setRelativePath(TSFCJob obj, int index) {
        String relativePath = "relativePath_" + index;
        if (relativePath.length() > 500) {
            relativePath = relativePath.substring(0, 500);
        }
        obj.setRelativePath(relativePath);
    }
    
    public void TSFCJobDataOnDemand.setSiteType(TSFCJob obj, int index) {
        ReactionSiteTypeEnum siteType = ReactionSiteTypeEnum.class.getEnumConstants()[0];
        obj.setSiteType(siteType);
    }
    
    public void TSFCJobDataOnDemand.setSpin(TSFCJob obj, int index) {
        Integer spin = new Integer(index);
        if (spin < 1) {
            spin = 1;
        }
        obj.setSpin(spin);
    }
    
    public void TSFCJobDataOnDemand.setStartGeometry(TSFCJob obj, int index) {
        String startGeometry = "startGeometry_" + index;
        if (startGeometry.length() > 5000) {
            startGeometry = startGeometry.substring(0, 5000);
        }
        obj.setStartGeometry(startGeometry);
    }
    
    public void TSFCJobDataOnDemand.setUniqueName(TSFCJob obj, int index) {
        String uniqueName = "uniqueName_" + index;
        if (uniqueName.length() > 100) {
            uniqueName = uniqueName.substring(0, 100);
        }
        obj.setUniqueName(uniqueName);
    }
    
    public void TSFCJobDataOnDemand.setUnrestrictedSpinGuess(TSFCJob obj, int index) {
        BigDecimal unrestrictedSpinGuess = BigDecimal.valueOf(index);
        if (unrestrictedSpinGuess.compareTo(new BigDecimal("999.999")) == 1) {
            unrestrictedSpinGuess = new BigDecimal("999.999");
        }
        obj.setUnrestrictedSpinGuess(unrestrictedSpinGuess);
    }
    
    public void TSFCJobDataOnDemand.setUnrestrictedSpinReal(TSFCJob obj, int index) {
        BigDecimal unrestrictedSpinReal = BigDecimal.valueOf(index);
        if (unrestrictedSpinReal.compareTo(new BigDecimal("999.999")) == 1) {
            unrestrictedSpinReal = new BigDecimal("999.999");
        }
        obj.setUnrestrictedSpinReal(unrestrictedSpinReal);
    }
    
    public void TSFCJobDataOnDemand.setZpe(TSFCJob obj, int index) {
        BigDecimal zpe = BigDecimal.valueOf(index);
        if (zpe.compareTo(new BigDecimal("99999.999")) == 1) {
            zpe = new BigDecimal("99999.999");
        }
        obj.setZpe(zpe);
    }
    
    public TSFCJob TSFCJobDataOnDemand.getSpecificTSFCJob(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TSFCJob obj = data.get(index);
        Long id = obj.getId();
        return TSFCJob.findTSFCJob(id);
    }
    
    public TSFCJob TSFCJobDataOnDemand.getRandomTSFCJob() {
        init();
        TSFCJob obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TSFCJob.findTSFCJob(id);
    }
    
    public boolean TSFCJobDataOnDemand.modifyTSFCJob(TSFCJob obj) {
        return false;
    }
    
    public void TSFCJobDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TSFCJob.findTSFCJobEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TSFCJob' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TSFCJob>();
        for (int i = 0; i < 10; i++) {
            TSFCJob obj = getNewTransientTSFCJob(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
