// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSNCStoredFiles;
import mingh.research.model.TSNCStoredFilesDataOnDemand;
import mingh.research.model.TSNCStoredFilesIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSNCStoredFilesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSNCStoredFilesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSNCStoredFilesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSNCStoredFilesIntegrationTest: @Transactional;
    
    @Autowired
    TSNCStoredFilesDataOnDemand TSNCStoredFilesIntegrationTest.dod;
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testCountTSNCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", dod.getRandomTSNCStoredFiles());
        long count = TSNCStoredFiles.countTSNCStoredFileses();
        Assert.assertTrue("Counter for 'TSNCStoredFiles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testFindTSNCStoredFiles() {
        TSNCStoredFiles obj = dod.getRandomTSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to provide an identifier", id);
        obj = TSNCStoredFiles.findTSNCStoredFiles(id);
        Assert.assertNotNull("Find method for 'TSNCStoredFiles' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSNCStoredFiles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testFindAllTSNCStoredFileses() {
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", dod.getRandomTSNCStoredFiles());
        long count = TSNCStoredFiles.countTSNCStoredFileses();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSNCStoredFiles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSNCStoredFiles> result = TSNCStoredFiles.findAllTSNCStoredFileses();
        Assert.assertNotNull("Find all method for 'TSNCStoredFiles' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSNCStoredFiles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testFindTSNCStoredFilesEntries() {
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", dod.getRandomTSNCStoredFiles());
        long count = TSNCStoredFiles.countTSNCStoredFileses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSNCStoredFiles> result = TSNCStoredFiles.findTSNCStoredFilesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSNCStoredFiles' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSNCStoredFiles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testFlush() {
        TSNCStoredFiles obj = dod.getRandomTSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to provide an identifier", id);
        obj = TSNCStoredFiles.findTSNCStoredFiles(id);
        Assert.assertNotNull("Find method for 'TSNCStoredFiles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSNCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSNCStoredFiles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testMergeUpdate() {
        TSNCStoredFiles obj = dod.getRandomTSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to provide an identifier", id);
        obj = TSNCStoredFiles.findTSNCStoredFiles(id);
        boolean modified =  dod.modifyTSNCStoredFiles(obj);
        Integer currentVersion = obj.getVersion();
        TSNCStoredFiles merged = (TSNCStoredFiles)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSNCStoredFiles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", dod.getRandomTSNCStoredFiles());
        TSNCStoredFiles obj = dod.getNewTransientTSNCStoredFiles(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSNCStoredFiles' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSNCStoredFiles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSNCStoredFilesIntegrationTest.testRemove() {
        TSNCStoredFiles obj = dod.getRandomTSNCStoredFiles();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCStoredFiles' failed to provide an identifier", id);
        obj = TSNCStoredFiles.findTSNCStoredFiles(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSNCStoredFiles' with identifier '" + id + "'", TSNCStoredFiles.findTSNCStoredFiles(id));
    }
    
}
