// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSNCJobStep;
import mingh.research.model.TSNCJobStepDataOnDemand;
import mingh.research.model.TSNCJobStepIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSNCJobStepIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSNCJobStepIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSNCJobStepIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSNCJobStepIntegrationTest: @Transactional;
    
    @Autowired
    TSNCJobStepDataOnDemand TSNCJobStepIntegrationTest.dod;
    
    @Test
    public void TSNCJobStepIntegrationTest.testCountTSNCJobSteps() {
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", dod.getRandomTSNCJobStep());
        long count = TSNCJobStep.countTSNCJobSteps();
        Assert.assertTrue("Counter for 'TSNCJobStep' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testFindTSNCJobStep() {
        TSNCJobStep obj = dod.getRandomTSNCJobStep();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to provide an identifier", id);
        obj = TSNCJobStep.findTSNCJobStep(id);
        Assert.assertNotNull("Find method for 'TSNCJobStep' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSNCJobStep' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testFindAllTSNCJobSteps() {
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", dod.getRandomTSNCJobStep());
        long count = TSNCJobStep.countTSNCJobSteps();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSNCJobStep', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSNCJobStep> result = TSNCJobStep.findAllTSNCJobSteps();
        Assert.assertNotNull("Find all method for 'TSNCJobStep' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSNCJobStep' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testFindTSNCJobStepEntries() {
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", dod.getRandomTSNCJobStep());
        long count = TSNCJobStep.countTSNCJobSteps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSNCJobStep> result = TSNCJobStep.findTSNCJobStepEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSNCJobStep' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSNCJobStep' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testFlush() {
        TSNCJobStep obj = dod.getRandomTSNCJobStep();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to provide an identifier", id);
        obj = TSNCJobStep.findTSNCJobStep(id);
        Assert.assertNotNull("Find method for 'TSNCJobStep' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSNCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSNCJobStep' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testMergeUpdate() {
        TSNCJobStep obj = dod.getRandomTSNCJobStep();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to provide an identifier", id);
        obj = TSNCJobStep.findTSNCJobStep(id);
        boolean modified =  dod.modifyTSNCJobStep(obj);
        Integer currentVersion = obj.getVersion();
        TSNCJobStep merged = (TSNCJobStep)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSNCJobStep' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", dod.getRandomTSNCJobStep());
        TSNCJobStep obj = dod.getNewTransientTSNCJobStep(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSNCJobStep' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSNCJobStep' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSNCJobStepIntegrationTest.testRemove() {
        TSNCJobStep obj = dod.getRandomTSNCJobStep();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCJobStep' failed to provide an identifier", id);
        obj = TSNCJobStep.findTSNCJobStep(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSNCJobStep' with identifier '" + id + "'", TSNCJobStep.findTSNCJobStep(id));
    }
    
}
