// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mingh.research.model.TSNCJobDataOnDemand;
import mingh.research.model.TSNCJobIRProperty;
import mingh.research.model.TSNCJobIRPropertyDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TSNCJobIRPropertyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TSNCJobIRPropertyDataOnDemand: @Component;
    
    private Random TSNCJobIRPropertyDataOnDemand.rnd = new SecureRandom();
    
    private List<TSNCJobIRProperty> TSNCJobIRPropertyDataOnDemand.data;
    
    @Autowired
    TSNCJobDataOnDemand TSNCJobIRPropertyDataOnDemand.tSNCJobDataOnDemand;
    
    public TSNCJobIRProperty TSNCJobIRPropertyDataOnDemand.getNewTransientTSNCJobIRProperty(int index) {
        TSNCJobIRProperty obj = new TSNCJobIRProperty();
        setCv(obj, index);
        setFreqNumbers(obj, index);
        setG(obj, index);
        setH(obj, index);
        setIntensities(obj, index);
        setNormModes(obj, index);
        setS(obj, index);
        setT(obj, index);
        setU(obj, index);
        setUniqueName(obj, index);
        return obj;
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setCv(TSNCJobIRProperty obj, int index) {
        BigDecimal Cv = BigDecimal.valueOf(index);
        if (Cv.compareTo(new BigDecimal("99999.999")) == 1) {
            Cv = new BigDecimal("99999.999");
        }
        obj.setCv(Cv);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setFreqNumbers(TSNCJobIRProperty obj, int index) {
        String freqNumbers = "freqNumbers_" + index;
        if (freqNumbers.length() > 20000) {
            freqNumbers = freqNumbers.substring(0, 20000);
        }
        obj.setFreqNumbers(freqNumbers);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setG(TSNCJobIRProperty obj, int index) {
        BigDecimal G = BigDecimal.valueOf(index);
        if (G.compareTo(new BigDecimal("99999.999")) == 1) {
            G = new BigDecimal("99999.999");
        }
        obj.setG(G);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setH(TSNCJobIRProperty obj, int index) {
        BigDecimal H = BigDecimal.valueOf(index);
        if (H.compareTo(new BigDecimal("99999.999")) == 1) {
            H = new BigDecimal("99999.999");
        }
        obj.setH(H);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setIntensities(TSNCJobIRProperty obj, int index) {
        String intensities = "intensities_" + index;
        if (intensities.length() > 20000) {
            intensities = intensities.substring(0, 20000);
        }
        obj.setIntensities(intensities);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setNormModes(TSNCJobIRProperty obj, int index) {
        byte[] normModes = String.valueOf(index).getBytes();
        obj.setNormModes(normModes);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setS(TSNCJobIRProperty obj, int index) {
        BigDecimal S = BigDecimal.valueOf(index);
        if (S.compareTo(new BigDecimal("99999.999")) == 1) {
            S = new BigDecimal("99999.999");
        }
        obj.setS(S);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setT(TSNCJobIRProperty obj, int index) {
        BigDecimal T = BigDecimal.valueOf(index);
        if (T.compareTo(new BigDecimal("99999.999")) == 1) {
            T = new BigDecimal("99999.999");
        }
        obj.setT(T);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setU(TSNCJobIRProperty obj, int index) {
        BigDecimal U = BigDecimal.valueOf(index);
        if (U.compareTo(new BigDecimal("99999.999")) == 1) {
            U = new BigDecimal("99999.999");
        }
        obj.setU(U);
    }
    
    public void TSNCJobIRPropertyDataOnDemand.setUniqueName(TSNCJobIRProperty obj, int index) {
        String uniqueName = "uniqueName_" + index;
        if (uniqueName.length() > 100) {
            uniqueName = uniqueName.substring(0, 100);
        }
        obj.setUniqueName(uniqueName);
    }
    
    public TSNCJobIRProperty TSNCJobIRPropertyDataOnDemand.getSpecificTSNCJobIRProperty(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TSNCJobIRProperty obj = data.get(index);
        Long id = obj.getId();
        return TSNCJobIRProperty.findTSNCJobIRProperty(id);
    }
    
    public TSNCJobIRProperty TSNCJobIRPropertyDataOnDemand.getRandomTSNCJobIRProperty() {
        init();
        TSNCJobIRProperty obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TSNCJobIRProperty.findTSNCJobIRProperty(id);
    }
    
    public boolean TSNCJobIRPropertyDataOnDemand.modifyTSNCJobIRProperty(TSNCJobIRProperty obj) {
        return false;
    }
    
    public void TSNCJobIRPropertyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TSNCJobIRProperty.findTSNCJobIRPropertyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TSNCJobIRProperty' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TSNCJobIRProperty>();
        for (int i = 0; i < 10; i++) {
            TSNCJobIRProperty obj = getNewTransientTSNCJobIRProperty(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
