// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mingh.research.model.TSNCJobDataOnDemand;
import mingh.research.model.TSNCJobStep;
import mingh.research.model.TSNCJobStepDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TSNCJobStepDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TSNCJobStepDataOnDemand: @Component;
    
    private Random TSNCJobStepDataOnDemand.rnd = new SecureRandom();
    
    private List<TSNCJobStep> TSNCJobStepDataOnDemand.data;
    
    @Autowired
    TSNCJobDataOnDemand TSNCJobStepDataOnDemand.tSNCJobDataOnDemand;
    
    public TSNCJobStep TSNCJobStepDataOnDemand.getNewTransientTSNCJobStep(int index) {
        TSNCJobStep obj = new TSNCJobStep();
        setAlphaHOMO(obj, index);
        setAlphaLUMO(obj, index);
        setAlphaOrbital(obj, index);
        setBetaHOMO(obj, index);
        setBetaLUMO(obj, index);
        setBetaOrbital(obj, index);
        setDetailedForce(obj, index);
        setEnergy(obj, index);
        setForce(obj, index);
        setGeometry(obj, index);
        setRelativePath(obj, index);
        setStep(obj, index);
        setUniqueName(obj, index);
        setUnrestrictedSpinGuess(obj, index);
        setUnrestrictedSpinReal(obj, index);
        return obj;
    }
    
    public void TSNCJobStepDataOnDemand.setAlphaHOMO(TSNCJobStep obj, int index) {
        BigDecimal alphaHOMO = BigDecimal.valueOf(index);
        if (alphaHOMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            alphaHOMO = new BigDecimal("99999.99999");
        }
        obj.setAlphaHOMO(alphaHOMO);
    }
    
    public void TSNCJobStepDataOnDemand.setAlphaLUMO(TSNCJobStep obj, int index) {
        BigDecimal alphaLUMO = BigDecimal.valueOf(index);
        if (alphaLUMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            alphaLUMO = new BigDecimal("99999.99999");
        }
        obj.setAlphaLUMO(alphaLUMO);
    }
    
    public void TSNCJobStepDataOnDemand.setAlphaOrbital(TSNCJobStep obj, int index) {
        String alphaOrbital = "alphaOrbital_" + index;
        if (alphaOrbital.length() > 20000) {
            alphaOrbital = alphaOrbital.substring(0, 20000);
        }
        obj.setAlphaOrbital(alphaOrbital);
    }
    
    public void TSNCJobStepDataOnDemand.setBetaHOMO(TSNCJobStep obj, int index) {
        BigDecimal betaHOMO = BigDecimal.valueOf(index);
        if (betaHOMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            betaHOMO = new BigDecimal("99999.99999");
        }
        obj.setBetaHOMO(betaHOMO);
    }
    
    public void TSNCJobStepDataOnDemand.setBetaLUMO(TSNCJobStep obj, int index) {
        BigDecimal betaLUMO = BigDecimal.valueOf(index);
        if (betaLUMO.compareTo(new BigDecimal("99999.99999")) == 1) {
            betaLUMO = new BigDecimal("99999.99999");
        }
        obj.setBetaLUMO(betaLUMO);
    }
    
    public void TSNCJobStepDataOnDemand.setBetaOrbital(TSNCJobStep obj, int index) {
        String betaOrbital = "betaOrbital_" + index;
        if (betaOrbital.length() > 20000) {
            betaOrbital = betaOrbital.substring(0, 20000);
        }
        obj.setBetaOrbital(betaOrbital);
    }
    
    public void TSNCJobStepDataOnDemand.setDetailedForce(TSNCJobStep obj, int index) {
        String detailedForce = "detailedForce_" + index;
        if (detailedForce.length() > 5000) {
            detailedForce = detailedForce.substring(0, 5000);
        }
        obj.setDetailedForce(detailedForce);
    }
    
    public void TSNCJobStepDataOnDemand.setEnergy(TSNCJobStep obj, int index) {
        BigDecimal energy = BigDecimal.valueOf(index);
        if (energy.compareTo(new BigDecimal("99999.99999")) == 1) {
            energy = new BigDecimal("99999.99999");
        }
        obj.setEnergy(energy);
    }
    
    public void TSNCJobStepDataOnDemand.setForce(TSNCJobStep obj, int index) {
        BigDecimal force = BigDecimal.valueOf(index);
        if (force.compareTo(new BigDecimal("99999.99999")) == 1) {
            force = new BigDecimal("99999.99999");
        }
        obj.setForce(force);
    }
    
    public void TSNCJobStepDataOnDemand.setGeometry(TSNCJobStep obj, int index) {
        String geometry = "geometry_" + index;
        if (geometry.length() > 5000) {
            geometry = geometry.substring(0, 5000);
        }
        obj.setGeometry(geometry);
    }
    
    public void TSNCJobStepDataOnDemand.setRelativePath(TSNCJobStep obj, int index) {
        String relativePath = "relativePath_" + index;
        if (relativePath.length() > 500) {
            relativePath = relativePath.substring(0, 500);
        }
        obj.setRelativePath(relativePath);
    }
    
    public void TSNCJobStepDataOnDemand.setStep(TSNCJobStep obj, int index) {
        Integer step = new Integer(index);
        if (step < 1) {
            step = 1;
        }
        obj.setStep(step);
    }
    
    public void TSNCJobStepDataOnDemand.setUniqueName(TSNCJobStep obj, int index) {
        String uniqueName = "uniqueName_" + index;
        if (uniqueName.length() > 100) {
            uniqueName = uniqueName.substring(0, 100);
        }
        obj.setUniqueName(uniqueName);
    }
    
    public void TSNCJobStepDataOnDemand.setUnrestrictedSpinGuess(TSNCJobStep obj, int index) {
        BigDecimal unrestrictedSpinGuess = BigDecimal.valueOf(index);
        if (unrestrictedSpinGuess.compareTo(new BigDecimal("999.999")) == 1) {
            unrestrictedSpinGuess = new BigDecimal("999.999");
        }
        obj.setUnrestrictedSpinGuess(unrestrictedSpinGuess);
    }
    
    public void TSNCJobStepDataOnDemand.setUnrestrictedSpinReal(TSNCJobStep obj, int index) {
        BigDecimal unrestrictedSpinReal = BigDecimal.valueOf(index);
        if (unrestrictedSpinReal.compareTo(new BigDecimal("999.999")) == 1) {
            unrestrictedSpinReal = new BigDecimal("999.999");
        }
        obj.setUnrestrictedSpinReal(unrestrictedSpinReal);
    }
    
    public TSNCJobStep TSNCJobStepDataOnDemand.getSpecificTSNCJobStep(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TSNCJobStep obj = data.get(index);
        Long id = obj.getId();
        return TSNCJobStep.findTSNCJobStep(id);
    }
    
    public TSNCJobStep TSNCJobStepDataOnDemand.getRandomTSNCJobStep() {
        init();
        TSNCJobStep obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TSNCJobStep.findTSNCJobStep(id);
    }
    
    public boolean TSNCJobStepDataOnDemand.modifyTSNCJobStep(TSNCJobStep obj) {
        return false;
    }
    
    public void TSNCJobStepDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TSNCJobStep.findTSNCJobStepEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TSNCJobStep' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TSNCJobStep>();
        for (int i = 0; i < 10; i++) {
            TSNCJobStep obj = getNewTransientTSNCJobStep(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
