// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import java.util.List;
import mingh.research.model.TSNCOptimizationProcess;
import mingh.research.model.TSNCOptimizationProcessDataOnDemand;
import mingh.research.model.TSNCOptimizationProcessIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TSNCOptimizationProcessIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TSNCOptimizationProcessIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TSNCOptimizationProcessIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TSNCOptimizationProcessIntegrationTest: @Transactional;
    
    @Autowired
    TSNCOptimizationProcessDataOnDemand TSNCOptimizationProcessIntegrationTest.dod;
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testCountTSNCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", dod.getRandomTSNCOptimizationProcess());
        long count = TSNCOptimizationProcess.countTSNCOptimizationProcesses();
        Assert.assertTrue("Counter for 'TSNCOptimizationProcess' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testFindTSNCOptimizationProcess() {
        TSNCOptimizationProcess obj = dod.getRandomTSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to provide an identifier", id);
        obj = TSNCOptimizationProcess.findTSNCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'TSNCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TSNCOptimizationProcess' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testFindAllTSNCOptimizationProcesses() {
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", dod.getRandomTSNCOptimizationProcess());
        long count = TSNCOptimizationProcess.countTSNCOptimizationProcesses();
        Assert.assertTrue("Too expensive to perform a find all test for 'TSNCOptimizationProcess', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TSNCOptimizationProcess> result = TSNCOptimizationProcess.findAllTSNCOptimizationProcesses();
        Assert.assertNotNull("Find all method for 'TSNCOptimizationProcess' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TSNCOptimizationProcess' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testFindTSNCOptimizationProcessEntries() {
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", dod.getRandomTSNCOptimizationProcess());
        long count = TSNCOptimizationProcess.countTSNCOptimizationProcesses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TSNCOptimizationProcess> result = TSNCOptimizationProcess.findTSNCOptimizationProcessEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TSNCOptimizationProcess' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TSNCOptimizationProcess' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testFlush() {
        TSNCOptimizationProcess obj = dod.getRandomTSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to provide an identifier", id);
        obj = TSNCOptimizationProcess.findTSNCOptimizationProcess(id);
        Assert.assertNotNull("Find method for 'TSNCOptimizationProcess' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTSNCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TSNCOptimizationProcess' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testMergeUpdate() {
        TSNCOptimizationProcess obj = dod.getRandomTSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to provide an identifier", id);
        obj = TSNCOptimizationProcess.findTSNCOptimizationProcess(id);
        boolean modified =  dod.modifyTSNCOptimizationProcess(obj);
        Integer currentVersion = obj.getVersion();
        TSNCOptimizationProcess merged = (TSNCOptimizationProcess)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TSNCOptimizationProcess' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", dod.getRandomTSNCOptimizationProcess());
        TSNCOptimizationProcess obj = dod.getNewTransientTSNCOptimizationProcess(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TSNCOptimizationProcess' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TSNCOptimizationProcess' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TSNCOptimizationProcessIntegrationTest.testRemove() {
        TSNCOptimizationProcess obj = dod.getRandomTSNCOptimizationProcess();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TSNCOptimizationProcess' failed to provide an identifier", id);
        obj = TSNCOptimizationProcess.findTSNCOptimizationProcess(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TSNCOptimizationProcess' with identifier '" + id + "'", TSNCOptimizationProcess.findTSNCOptimizationProcess(id));
    }
    
}
