// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mingh.research.model;

import javax.persistence.Entity;
import mingh.research.model.TSNCOptimizationProcess;

privileged aspect TSNCOptimizationProcess_Roo_Jpa_Entity {
    
    declare @type: TSNCOptimizationProcess: @Entity;
    
}
